local SM = LibStub("LibSharedMedia-3.0")

local path = "Interface\\AddOns\\InvenRaidFrames3\\"

SM:Register("statusbar", "Charcoal", path.."Texture\\Charcoal")
SM:Register("statusbar", "Glaze", path.."Texture\\Glaze")
SM:Register("statusbar", "Gloss", path.."Texture\\Gloss")
SM:Register("statusbar", "Halycon", path.."Texture\\Halycon")
SM:Register("statusbar", "Melli", path.."Texture\\Melli")
SM:Register("statusbar", "Pill", path.."Texture\\Pill")
SM:Register("statusbar", "Smooth", path.."Texture\\Smooth")
SM:Register("statusbar", "Smooth v2", path.."Texture\\Smoothv2")
SM:Register("statusbar", "Steel", path.."Texture\\Steel")
SM:Register("statusbar", "Gradient", path.."Texture\\Gradient")

SM:Register("sound", "어그로", path.."Sound\\Aggro.mp3")
SM:Register("sound", "띵동", path.."Sound\\DingDong.mp3")
SM:Register("sound", "Explosion", "Sound\\Doodad\\Hellfire_Raid_FX_Explosion05.ogg")
SM:Register("sound", "Wham!", "Sound\\Doodad\\PVP_Lordaeron_Door_Open.ogg")
SM:Register("sound", "Simon Chime", "Sound\\Doodad\\SimonGame_LargeBlueTree.ogg")
SM:Register("sound", "War Drums", "Sound\\Event Sounds\\Event_wardrum_ogre.ogg")
SM:Register("sound", "Cheer", "Sound\\Event Sounds\\OgreEventCheerUnique.ogg")
SM:Register("sound", "Humm", "Sound\\Spells\\SimonGame_Visual_GameStart.ogg")
SM:Register("sound", "Fel Portal", "Sound\\Spells\\Sunwell_Fel_PortalStand.ogg")
SM:Register("sound", "Fel Nova", "Sound\\Spells\\SeepingGaseous_Fel_Nova.ogg")
SM:Register("sound", "Blizzard: Bell - Alliance", "Sound\\Doodad\\BellTollAlliance.ogg")
SM:Register("sound", "Blizzard: Bell - Horde", "Sound\\Doodad\\BellTollHorde.ogg")
SM:Register("sound", "Blizzard: Bell - Night Elf", "Sound\\Doodad\\BellTollNightElf.ogg")
SM:Register("sound", "Blizzard: Drum Hit", "Sound\\Doodad\\BellTollTribal.ogg")
SM:Register("sound", "Blizzard: Bells - Boat Arrived", "Sound\\Doodad\\BoatDockedWarning.ogg")
SM:Register("sound", "Blizzard: Gong - Troll", "Sound\\Doodad\\G_GongTroll01.ogg")
SM:Register("sound", "Blizzard: Mellow Bells", "Sound\\Spells\\ShaysBell.ogg")
SM:Register("sound", "Blizzard: Enter Queue", "Sound\\Spells\\PVPEnterQueue.ogg")
SM:Register("sound", "Blizzard: Hearthstone Bind", "Sound\\Spells\\bind2_Impact_Base.ogg")
SM:Register("sound", "Blizzard: Karazhan Bell" , "Sound\\Doodad\\KharazahnBellToll.ogg")
SM:Register("sound", "Blizzard: Auction Ding", "Sound\\Interface\\AuctionWindowOpen.ogg")
SM:Register("sound", "Blizzard: Auction Bells", "Sound\\Interface\\AuctionWindowClose.ogg")
SM:Register("sound", "Blizzard: Alarm Clock 1", "Sound\\Interface\\AlarmClockWarning1.ogg")
SM:Register("sound", "Blizzard: Alarm Clock 2", "Sound\\Interface\\AlarmClockWarning2.ogg")
SM:Register("sound", "Blizzard: Alarm Clock 3", "Sound\\Interface\\AlarmClockWarning3.ogg")
SM:Register("sound", "Blizzard: Map Ping", "Sound\\Interface\\MapPing.ogg")
SM:Register("sound", "Blizzard: Simon Ding", "Sound\\Spells\\SimonGame_Visual_GameTick.ogg")
SM:Register("sound", "Blizzard: Simon Start Game", "Sound\\Spells\\SimonGame_Visual_LevelStart.ogg")
SM:Register("sound", "Blizzard: Simon Start Level", "Sound\\Spells\\SimonGame_Visual_GameStart.ogg")
SM:Register("sound", "Blizzard: Yarrrr", "Sound\\Spells\\YarrrrImpact.ogg")