--
--	JSHB Options - target bar panel
--

local L = _G.JSHB.L

function JSHB.Options:Panel_TargetBar(ord)
	local DB = _G.JSHB.Options.DB
	return {
		order = ord,
		type = "group",
		name = L["Target Bar"],
		childGroups = "tab",
		args = {
			maintab = {
				order = 1,
				type = "group",
				name = L["Target Bar"],
				args = {
					enabled = {
						type = "toggle",
						order = 2,
						name = L["Enable"],
						width = "double",
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) JSHB.Options:CollapseAll(); DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					smoothbar = {
						type = "toggle",
						order = 6,
						name = L["Bar smoothing"],
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					healthnumber = {
						type = "toggle",
						order = 8,
						name = L["Current health number"],
						desc = L["RESOURCEBARNUMBERDESC_ENABLE"],
						width = "double",
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					targethealth = {
						type = "toggle",
						order = 10,
						name = L["Target health percentage"],
						width = "full",
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					spacer17 = { order = 17, type = "description", name = " ", desc = "", width = "full"},
					width = {
						type = "range", 
						order = 22,
						name = L["Width"],
						min = 6, softMax = 600, max = 1000, step = 1,
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return (DB.targetbar[info[#info] ]) end,
						set = function(info, size) DB.targetbar[info[#info] ] = (size);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					spacer24 = { order = 24, type = "description", name = " ", desc = "", width = "half" },
					height = {
						type = "range", 
						order = 26,
						name = L["Height"],
						min = 6, softMax = 600, max = 1000, step = 1,
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return (DB.targetbar[info[#info] ]) end,
						set = function(info, size) DB.targetbar[info[#info] ] = (size);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					spacer27 = { order = 27, type = "description", name = " ", desc = "", width = "full" },
					bartexture = {
						type = "select",
						dialogControl = 'LSM30_Statusbar',
						order = 28,
						name = L["Texture"],
						values = AceGUIWidgetLSMlists.statusbar,
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					spacer29 = { order = 29, type = "description", name = " ", desc = "", width = "full" },
					classcolored = {
						type = "toggle",
						order = 30,
						name = L["Use class colors for the bar"],
						width = "double",
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					spacer32 = { order = 32, type = "description", name = " ", desc = "", hidden = function(info) return (not DB.targetbar.classcolored) end },
					barcolor = {
						type = "color",
						order = 34,
						name = L["Normal color"],
						desc = L["RESOURCEBARCOLORNORM_DESC"],
						hasAlpha = true,
						hidden = function(info) return (DB.targetbar.classcolored) end,
						get = function(info) return unpack(DB.targetbar[info[#info] ]) end,
						set = function(info, r, g, b, a) DB.targetbar[info[#info] ] = {r, g, b, a};JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					lowwarn = {
						type = "toggle",
						order = 36,
						name = L["Low resource change"],
						desc = L["RESOURCEBARLOWWARNDESC_ENABLE"],
						width = "double",
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					lowwarnthreshold = {
						type = "range", 
						order = 44,
						name = L["Low warning %"],
						desc = L["RESOURCEBARHIGHWARNTHRESHOLD_DESC"],
						disabled = function(info) return not DB.targetbar["enabled"] end,
						hidden = function(info) return(not DB.targetbar.lowwarn) end,
						isPercent = true,
						min = .1, max = 1, step = .05,
						get = function(info) return(DB.targetbar[info[#info] ]) end,
						set = function(info, size) DB.targetbar[info[#info] ] = (size);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					spacer38 = { order = 38, type = "description", name = " ", desc = "", width = "half", hidden = function(info) return(DB.targetbar.lowwarn) end },
					barcolorlow = {
						type = "color",
						order = 40,
						name = L["Low color"],
						desc = L["RESOURCEBARCOLORNORM_DESC"],
						hasAlpha = true,
						hidden = function(info) return not DB.targetbar.lowwarn end,
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return unpack(DB.targetbar[info[#info] ]) end,
						set = function(info, r, g, b, a) DB.targetbar[info[#info] ] = {r, g, b, a};JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
				},
			},
			alphastuff = {
				order = 6,
				type = "group",
				name = L["Bar alpha"],
				disabled = function(info) return not DB.targetbar["enabled"] end,
				args = {
					activealpha = {
						type = "range",
						order = 24,
						name = L["Active alpha"],
						desc = L["RESOURCEBARACTIVEALPHA_DESC"],
						min = 0, max = 1, step = .1,
						isPercent = true,
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return (DB.targetbar[info[#info] ]) end,
						set = function(info, value) DB.targetbar[info[#info] ] = (value);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					inactivealpha = {
						type = "range",
						order = 26,
						name = L["Inactive alpha"],
						desc = L["RESOURCEBARINACTIVEALPHA_DESC"],
						min = 0, max = 1, step = .1,
						isPercent = true,
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return (DB.targetbar[info[#info] ]) end,
						set = function(info, value) DB.targetbar[info[#info] ] = (value);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					spacer27 = { order = 27, type = "description", name = " ", desc = "", width = "full"},
					oocoverride = {
						type = "toggle",
						order = 28,
						name = L["OOC override"],
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					mountoverride = {
						type = "toggle",
						order = 32,
						name = L["Mounted override"],
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					deadoverride = {
						type = "toggle",
						order = 34,
						name = L["Dead override"],
						disabled = function(info) return not DB.targetbar["enabled"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					spacer36 = { order = 36, type = "description", name = " ", desc = "", width = "full"},
					oocoverridealpha = {
						type = "range",
						order = 38,
						name = L["OOC alpha"],
						min = 0, max = 1, step = .1,
						isPercent = true,
						disabled = function(info) 
							if not DB.targetbar["oocoverride"] then return true end
							if not DB.targetbar["enabled"] then return true end
							return false end,
						get = function(info) return (DB.targetbar[info[#info] ]) end,
						set = function(info, value) DB.targetbar[info[#info] ] = (value);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					mountoverridealpha = {
						type = "range",
						order = 40,
						name = L["Mounted alpha"],
						min = 0, max = 1, step = .1,
						isPercent = true,
						disabled = function(info) 
							if not DB.targetbar["mountoverride"] then return true end
							if not DB.targetbar["enabled"] then return true end
							return false end,
						get = function(info) return (DB.targetbar[info[#info] ]) end,
						set = function(info, value) DB.targetbar[info[#info] ] = (value);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					deadoverridealpha = {
						type = "range",
						order = 42,
						name = L["Dead alpha"],
						desc = L["RESOURCEBARDEADALPHA_DESC"],
						min = 0, max = 1, step = .1,
						isPercent = true,
						disabled = function(info) 
							if not DB.targetbar["deadoverride"] then return true end
							if not DB.targetbar["enabled"] then return true end
							return false end,
						get = function(info) return (DB.targetbar[info[#info] ]) end,
						set = function(info, value) DB.targetbar[info[#info] ] = (value);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
				},
			},
			fonts = {
				type = "group",
				order = 18,
				name = L["Fonts"],
				disabled = function(info) return not DB.targetbar["enabled"] end,
				args = {
					healthfont = {
						type = "group",
						order = 26,
						name = L["Resource font"],
						guiInline = true,
						args = {
							healthfontcolor = {
								type = "color",
								order = 2,
								name = L["Color"],
								desc = L["Color of the text showing your current resource."],
								hasAlpha = true,
								get = function(info) return unpack(DB.targetbar[info[#info] ]) end,
								set = function(info, r, g, b, a) DB.targetbar[info[#info] ] = {r, g, b, a};JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},
							healthfontoffset = {
								type = "range", 
								order = 4,
								name = L["Resource offset"],
								desc = L["DESC_RESOURCEBARFONTOFFSET"],
								min = -900, softMin = -100, softMax = 100, max = 900, step = 1,
								get = function(info) return (DB.targetbar[info[#info] ]) end,
								set = function(info, size) DB.targetbar[info[#info] ] = (size);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},
							spacer5 = { order = 5, type = "description", name = " ", desc = "", width = "half" },
							font = {
								type = "select", 
								dialogControl = "LSM30_Font",
								order = 6,
								name = L["Font face"],
								values = AceGUIWidgetLSMlists.font,
								get = function(info) return DB.targetbar[info[#info-1] ][1] end,
								set = function(info, font) DB.targetbar[info[#info-1] ][1] = font;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},
							size = {
								type = "range", 
								order = 8,
								name = L["Font size"],
								min = 6, max = 40, step = 1,
								get = function(info) return (DB.targetbar[info[#info-1] ][2]) end,
								set = function(info, size) DB.targetbar[info[#info-1] ][2] = (size);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},
							flags = {
								type = "multiselect", 
								order = 12,
								name = L["Font flags"],
								values = JSHB.Options.fontFlagTable,
								get = function(info, key) return(tContains({strsplit(",", DB.targetbar[info[#info-1] ][3])}, key) and true or false) end,
								set = function(info, keyname, state) JSHB.Options:SetupFontFlags(DB.targetbar[info[#info-1] ], keyname, state);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},
						},
					},
				},
			},
			backdrop = {
				type = "group",
				order = 22,
				name = L["Backdrop"],
				disabled = function(info) return not DB.targetbar["enabled"] end,
				args = {
					enablebackdrop = {
						type = "toggle",
						order = 1,
						name = L["Enable"],
						width = "double",
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					backdroptexture = {
						type = "select",
						dialogControl = 'LSM30_Background',
						order = 2,
						name = L["Backdrop texture"],
						values = AceGUIWidgetLSMlists.background,
						disabled = function(info) return not DB.targetbar["enablebackdrop"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					colorbackdrop = {
						type = "toggle",
						order = 3,
						name = L["Color the backdrop"],
						disabled = function(info) return not DB.targetbar["enablebackdrop"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					backdropcolor = {
						type = "color",
						order = 5,
						name = L["Backdrop color"],
						hasAlpha = true,
						disabled = function(info) return not DB.targetbar["enablebackdrop"] end,
						hidden = function(info) return not DB.targetbar.colorbackdrop end,
						get = function(info) return unpack(DB.targetbar[info[#info] ]) end,
						set = function(info, r, g, b, a) DB.targetbar[info[#info] ] = {r, g, b, a};JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					spacer6 = { order = 6, type = "description", name = " ", desc = "", width = "half", hidden = function(info) return not DB.targetbar.colorbackdrop end },
					tile = {
						type = "toggle",
						order = 7,
						name = L["Tile the backdrop"],
						disabled = function(info) return not DB.targetbar["enablebackdrop"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					tilesize = {
						type = "range",
						order = 8,
						name = L["Tile size"],
						min = -100, softMin = -30, softMax = 30, max = 100, step = 1,
						disabled = function(info) return not DB.targetbar["enablebackdrop"] end,
						hidden = function(info) return not DB.targetbar.tile end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					spacer = { order = 11, type = "description", name = "", desc = "", width = "full"},
					backdropoffsets = {
						type = "group",
						order = 14,
						name = L["Offsets"],
						guiInline = true,
						args = {
							offsetX1 = {
								type = "range",
								order = 1,
								name = L["Top-left X"],
								min = -50, softMin = -10, softMax = 0, max = 50, step = 1,
								disabled = function(info) return not DB.targetbar["enablebackdrop"] end,
								get = function(info) return (DB.targetbar[info[#info-1] ][1]) end,
								set = function(info, offset) DB.targetbar[info[#info-1] ][1] = (offset);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},
							offsetY1 = {
								type = "range", 
								order = 2,
								name = L["Top-left Y"],
								min = -50, softMin = 0, softMax = 10, max = 50, step = 1,
								disabled = function(info) return not DB.targetbar["enablebackdrop"] end,
								get = function(info) return (DB.targetbar[info[#info-1] ][2]) end,
								set = function(info, offset) DB.targetbar[info[#info-1] ][2] = (offset);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},
							spacer6 = { order = 6, type = "description", name = "", desc = "", width = "half"},
							offsetX2 = {
								type = "range", 
								order = 8,
								name = L["Bottom-right X"],
								min = -50, softMin = 0, softMax = 10, max = 50, step = 1,
								disabled = function(info) return not DB.targetbar["enablebackdrop"] end,
								get = function(info) return (DB.targetbar[info[#info-1] ][3]) end,
								set = function(info, offset) DB.targetbar[info[#info-1] ][3] = (offset);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},
							offsetY2 = {
								type = "range", 
								order = 10,
								name = L["Bottom-right Y"],
								min = -50, softMin = -10, softMax = 0, max = 50, step = 1,
								disabled = function(info) return not DB.targetbar["enablebackdrop"] end,
								get = function(info) return (DB.targetbar[info[#info-1] ][4]) end,
								set = function(info, offset) DB.targetbar[info[#info-1] ][4] = (offset);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},										
						},
					},
					spacer = { order = 16, type = "description", name = "", desc = "", width = "full"},
				},
			},
			border = {
				type = "group",
				order = 24,
				name = L["Border"],
				disabled = function(info) return not DB.targetbar["enabled"] end,
				args = {
					enableborder = {
						type = "toggle",
						order = 1,
						name = L["Enable"],
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					bordercolor = {
						type = "color",
						order = 2,
						name = L["Border color"],
						hasAlpha = true,
						disabled = function(info) return not DB.targetbar["enableborder"] end,
						get = function(info) return unpack(DB.targetbar[info[#info] ]) end,
						set = function(info, r, g, b, a) DB.targetbar[info[#info] ] = {r, g, b, a};JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					bordertexture = {
						type = "select",
						dialogControl = 'LSM30_Border',
						order = 3,
						name = L["Border texture"],
						values = AceGUIWidgetLSMlists.border,
						disabled = function(info) return not DB.targetbar["enableborder"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					edgesize = {
						type = "range",
						order = 4,
						name = L["Edge size"],
						min = -100, softMin = -16, softMax = 16, max = 100, step = 1,
						disabled = function(info) return not DB.targetbar["enableborder"] end,
						get = function(info) return DB.targetbar[info[#info] ] end,
						set = function(info, value) DB.targetbar[info[#info] ] = value;JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
					},
					spacer = { order = 7, type = "description", name = "", desc = "", width = "full"},
					backdropinsets = {
						type = "group",
						order = 10,
						name = L["Insets"],
						guiInline = true,
						args = {
							left = {
								type = "range",
								order = 1,
								name = L["Left"],
								min = -50, softMin = -16, softMax = 16, max = 50, step = 1,
								disabled = function(info) return not DB.targetbar["enableborder"] end,
								get = function(info) return (DB.targetbar[info[#info-1] ][1]) end,
								set = function(info, offset) DB.targetbar[info[#info-1] ][1] = (offset);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},
							right = {
								type = "range", 
								order = 2,
								name = L["Right"],
								min = -50, softMin = -16, softMax = 16, max = 50, step = 1,
								disabled = function(info) return not DB.targetbar["enableborder"] end,
								get = function(info) return (DB.targetbar[info[#info-1] ][2]) end,
								set = function(info, offset) DB.targetbar[info[#info-1] ][2] = (offset);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},
							top = {
								type = "range", 
								order = 3,
								name = L["Top"],
								min = -50, softMin = -16, softMax = 16, max = 50, step = 1,
								disabled = function(info) return not DB.targetbar["enableborder"] end,
								get = function(info) return (DB.targetbar[info[#info-1] ][3]) end,
								set = function(info, offset) DB.targetbar[info[#info-1] ][3] = (offset);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},
							bottom = {
								type = "range", 
								order = 4,
								name = L["Bottom"],
								min = -50, softMin = -16, softMax = 16, max = 50, step = 1,
								disabled = function(info) return not DB.targetbar["enableborder"] end,
								get = function(info) return (DB.targetbar[info[#info-1] ][4]) end,
								set = function(info, offset) DB.targetbar[info[#info-1] ][4] = (offset);JSHB.Options:LockDown(JSHB.SetupTargetBarModule) end,
							},										
						},
					},
				},
			},
		},
	}
end
